require("shulhi.opts")
require("shulhi.plugs")
require("shulhi.colorscheme")

require("shulhi.lsp.mason")
require("shulhi.lsp.autocomplete")
require("shulhi.plugins.formatter")
require("shulhi.plugins.telescope")
require("shulhi.plugins.treesitter")
require("shulhi.plugins.statusline")
require("shulhi.plugins.nvim_tree")
